// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBygiHbu8v94OvP30I5F0WvKhVTDabur_g',
    appId: '1:454096661669:web:81e03534573eeead5ab14c',
    messagingSenderId: '454096661669',
    projectId: 'setall-c899a',
    authDomain: 'setall-c899a.firebaseapp.com',
    storageBucket: 'setall-c899a.firebasestorage.app',
    measurementId: 'G-50YY4WSTL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHGm-c5a1rHh4V9KWWLUyltlWIPEorkEc',
    appId: '1:454096661669:android:704781cd8cd9ef825ab14c',
    messagingSenderId: '454096661669',
    projectId: 'setall-c899a',
    storageBucket: 'setall-c899a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSWMS890fqvPxurNLiY0nDuN6X45nOS2U',
    appId: '1:454096661669:ios:16e6a711874f61445ab14c',
    messagingSenderId: '454096661669',
    projectId: 'setall-c899a',
    storageBucket: 'setall-c899a.firebasestorage.app',
    iosBundleId: 'com.jafa.setall.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSWMS890fqvPxurNLiY0nDuN6X45nOS2U',
    appId: '1:454096661669:ios:5481e839680ae0ef5ab14c',
    messagingSenderId: '454096661669',
    projectId: 'setall-c899a',
    storageBucket: 'setall-c899a.firebasestorage.app',
    iosBundleId: 'com.setall.setall',
  );
}
