import json

new_keys = {
    'regional': {
        'en': {
            'date_time_format': 'Date & Time Format',
            'date_time_subtitle': 'Affects how dates are shown throughout the app.',
            'system_locale': 'System locale',
            'active': 'Active',
            'manual_override': 'Manual override',
            'manual_override_subtitle': 'Choose a specific date format instead of using the system default.',
            'time_format': 'Time Format',
            'time_format_subtitle': 'Affects how times are shown throughout the app.',
            'system_time_format': 'System time format',
            'manual_time_subtitle': 'Choose 24h or AM/PM instead of the system default.',
            'preview': 'Preview',
        },
        'de': {
            'date_time_format': 'Datum & Uhrzeit Format',
            'date_time_subtitle': 'Beeinflusst die Datumsanzeige in der gesamten App.',
            'system_locale': 'Systemgebietsschema',
            'active': 'Aktiv',
            'manual_override': 'Manuelle Einstellung',
            'manual_override_subtitle': 'Wähle ein bestimmtes Datumsformat statt der Systemvorgabe.',
            'time_format': 'Zeitformat',
            'time_format_subtitle': 'Beeinflusst die Zeitanzeige in der gesamten App.',
            'system_time_format': 'Systemzeitformat',
            'manual_time_subtitle': 'Wähle 24h oder AM/PM statt der Systemvorgabe.',
            'preview': 'Vorschau',
        },
        'es': {
            'date_time_format': 'Formato de fecha y hora',
            'date_time_subtitle': 'Afecta cómo se muestran las fechas en toda la app.',
            'system_locale': 'Configuración regional del sistema',
            'active': 'Activo',
            'manual_override': 'Configuración manual',
            'manual_override_subtitle': 'Elige un formato de fecha específico en lugar del predeterminado.',
            'time_format': 'Formato de hora',
            'time_format_subtitle': 'Afecta cómo se muestran las horas en toda la app.',
            'system_time_format': 'Formato de hora del sistema',
            'manual_time_subtitle': 'Elige 24h o AM/PM en lugar del predeterminado del sistema.',
            'preview': 'Vista previa',
        },
        'fr': {
            'date_time_format': 'Format de date et heure',
            'date_time_subtitle': 'Affecte l\'affichage des dates dans toute l\'application.',
            'system_locale': 'Paramètres régionaux du système',
            'active': 'Actif',
            'manual_override': 'Réglage manuel',
            'manual_override_subtitle': 'Choisissez un format de date spécifique au lieu du format système.',
            'time_format': 'Format d\'heure',
            'time_format_subtitle': 'Affecte l\'affichage des heures dans toute l\'application.',
            'system_time_format': 'Format d\'heure du système',
            'manual_time_subtitle': 'Choisissez 24h ou AM/PM au lieu du format système.',
            'preview': 'Aperçu',
        },
        'ka': {
            'date_time_format': 'თარიღისა და დროის ფორმატი',
            'date_time_subtitle': 'გავლენას ახდენს თარიღების ჩვენებაზე მთელ აპლიკაციაში.',
            'system_locale': 'სისტემის ლოკალი',
            'active': 'აქტიური',
            'manual_override': 'ხელით პარამეტრი',
            'manual_override_subtitle': 'აირჩიეთ კონკრეტული თარიღის ფორმატი სისტემის ნაცვლად.',
            'time_format': 'დროის ფორმატი',
            'time_format_subtitle': 'გავლენას ახდენს დროის ჩვენებაზე მთელ აპლიკაციაში.',
            'system_time_format': 'სისტემის დროის ფორმატი',
            'manual_time_subtitle': 'აირჩიეთ 24 საათი ან AM/PM სისტემის ნაცვლად.',
            'preview': 'გადახედვა',
        },
        'ru': {
            'date_time_format': 'Формат даты и времени',
            'date_time_subtitle': 'Влияет на отображение дат во всём приложении.',
            'system_locale': 'Системная локаль',
            'active': 'Активен',
            'manual_override': 'Ручная настройка',
            'manual_override_subtitle': 'Выберите конкретный формат даты вместо системного.',
            'time_format': 'Формат времени',
            'time_format_subtitle': 'Влияет на отображение времени во всём приложении.',
            'system_time_format': 'Системный формат времени',
            'manual_time_subtitle': 'Выберите 24ч или AM/PM вместо системного формата.',
            'preview': 'Предпросмотр',
        },
    },
    'notifications': {
        'en': {
            'push': 'Push',
            'email': 'Email',
            'new_expenses': 'New expenses',
            'new_expenses_sub': 'When an expense or income is added',
            'settlements': 'Settlements',
            'settlements_sub': 'When a balance is settled',
            'group_events': 'Group events',
            'group_events_sub': 'New members, group creation',
            'group_activity': 'Group activity',
            'group_activity_sub': 'When members add or change expenses',
            'weekly_digest': 'Weekly digest',
            'weekly_digest_sub': 'Activity summary every Monday',
            'push_note': 'Push delivery requires Firebase Cloud Messaging (FCM) or APNs to be configured in the server. Preferences below are saved and will take effect once the push service is wired up.',
        },
        'de': {
            'push': 'Push',
            'email': 'E-Mail',
            'new_expenses': 'Neue Ausgaben',
            'new_expenses_sub': 'Wenn eine Ausgabe oder Einnahme hinzugefügt wird',
            'settlements': 'Abrechnungen',
            'settlements_sub': 'Wenn ein Saldo ausgeglichen wird',
            'group_events': 'Gruppenereignisse',
            'group_events_sub': 'Neue Mitglieder, Gruppenerstellung',
            'group_activity': 'Gruppenaktivität',
            'group_activity_sub': 'Wenn Mitglieder Ausgaben hinzufügen oder ändern',
            'weekly_digest': 'Wöchentliche Zusammenfassung',
            'weekly_digest_sub': 'Aktivitätszusammenfassung jeden Montag',
            'push_note': 'Push-Zustellung erfordert FCM oder APNs auf dem Server. Einstellungen werden gespeichert und wirksam, sobald der Push-Dienst eingerichtet ist.',
        },
        'es': {
            'push': 'Push',
            'email': 'Correo',
            'new_expenses': 'Nuevos gastos',
            'new_expenses_sub': 'Cuando se agrega un gasto o ingreso',
            'settlements': 'Liquidaciones',
            'settlements_sub': 'Cuando se liquida un saldo',
            'group_events': 'Eventos de grupo',
            'group_events_sub': 'Nuevos miembros, creación de grupo',
            'group_activity': 'Actividad del grupo',
            'group_activity_sub': 'Cuando los miembros agregan o cambian gastos',
            'weekly_digest': 'Resumen semanal',
            'weekly_digest_sub': 'Resumen de actividad cada lunes',
            'push_note': 'La entrega push requiere FCM o APNs configurado en el servidor. Las preferencias se guardan y tendrán efecto cuando el servicio push esté listo.',
        },
        'fr': {
            'push': 'Push',
            'email': 'E-mail',
            'new_expenses': 'Nouvelles dépenses',
            'new_expenses_sub': 'Quand une dépense ou un revenu est ajouté',
            'settlements': 'Règlements',
            'settlements_sub': 'Quand un solde est réglé',
            'group_events': 'Événements de groupe',
            'group_events_sub': 'Nouveaux membres, création de groupe',
            'group_activity': 'Activité du groupe',
            'group_activity_sub': 'Quand les membres ajoutent ou modifient des dépenses',
            'weekly_digest': 'Résumé hebdomadaire',
            'weekly_digest_sub': 'Résumé d\'activité chaque lundi',
            'push_note': 'La livraison push nécessite FCM ou APNs configuré sur le serveur. Les préférences sont sauvegardées et prendront effet une fois le service push configuré.',
        },
        'ka': {
            'push': 'პუშ',
            'email': 'ელ-ფოსტა',
            'new_expenses': 'ახალი ხარჯები',
            'new_expenses_sub': 'როდესაც ხარჯი ან შემოსავალი ემატება',
            'settlements': 'ანგარიშსწორებები',
            'settlements_sub': 'როდესაც ბალანსი ანგარიშსწორდება',
            'group_events': 'ჯგუფის მოვლენები',
            'group_events_sub': 'ახალი წევრები, ჯგუფის შექმნა',
            'group_activity': 'ჯგუფის აქტივობა',
            'group_activity_sub': 'როდესაც წევრები ხარჯებს ამატებენ ან ცვლიან',
            'weekly_digest': 'კვირეული შეჯამება',
            'weekly_digest_sub': 'ყოველ ორშაბათს აქტივობის შეჯამება',
            'push_note': 'პუშ-შეტყობინებები საჭიროებს FCM ან APNs კონფიგურაციას სერვერზე.',
        },
        'ru': {
            'push': 'Push',
            'email': 'Email',
            'new_expenses': 'Новые расходы',
            'new_expenses_sub': 'Когда добавляется расход или доход',
            'settlements': 'Взаиморасчёты',
            'settlements_sub': 'Когда баланс погашается',
            'group_events': 'События группы',
            'group_events_sub': 'Новые участники, создание группы',
            'group_activity': 'Активность группы',
            'group_activity_sub': 'Когда участники добавляют или изменяют расходы',
            'weekly_digest': 'Еженедельный дайджест',
            'weekly_digest_sub': 'Сводка активности каждый понедельник',
            'push_note': 'Push-уведомления требуют настройки FCM или APNs на сервере. Настройки сохраняются и вступят в силу после подключения push-сервиса.',
        },
    },
    'data_privacy': {
        'en': {
            'title': 'Data & Privacy',
            'local_data': 'LOCAL DATA',
            'cloud_data': 'CLOUD DATA',
            'wallet_entries': 'Wallet entries',
            'group_expenses': 'Group expenses',
            'groups': 'Groups',
            'ai_chat_sessions': 'AI chat sessions',
            'wallet_synced': 'Wallet entries (synced)',
            'group_expenses_synced': 'Group expenses (synced)',
            'groups_created': 'Groups created',
            'download_report': 'Download report',
            'wallet_report': 'Wallet report',
            'wallet_report_sub': 'Your personal wallet entries as PDF',
            'groups_report': 'Groups report',
            'groups_report_sub': 'All your group expenses as PDF',
            'export_data': 'Export My Data',
            'privacy_policy': 'Privacy Policy',
            'export_failed': 'Export failed: {error}',
            'json_export': 'JSON \u2014 full export',
            'csv_export': 'CSV \u2014 spreadsheet',
            'pdf_report': 'PDF report',
        },
        'de': {
            'title': 'Daten & Datenschutz',
            'local_data': 'LOKALE DATEN',
            'cloud_data': 'CLOUD-DATEN',
            'wallet_entries': 'Wallet-Einträge',
            'group_expenses': 'Gruppenausgaben',
            'groups': 'Gruppen',
            'ai_chat_sessions': 'KI-Chat-Sitzungen',
            'wallet_synced': 'Wallet-Einträge (synchronisiert)',
            'group_expenses_synced': 'Gruppenausgaben (synchronisiert)',
            'groups_created': 'Erstellte Gruppen',
            'download_report': 'Bericht herunterladen',
            'wallet_report': 'Wallet-Bericht',
            'wallet_report_sub': 'Deine persönlichen Wallet-Einträge als PDF',
            'groups_report': 'Gruppenbericht',
            'groups_report_sub': 'Alle deine Gruppenausgaben als PDF',
            'export_data': 'Meine Daten exportieren',
            'privacy_policy': 'Datenschutzerklärung',
            'export_failed': 'Export fehlgeschlagen: {error}',
            'json_export': 'JSON \u2014 vollständiger Export',
            'csv_export': 'CSV \u2014 Tabelle',
            'pdf_report': 'PDF-Bericht',
        },
        'es': {
            'title': 'Datos y privacidad',
            'local_data': 'DATOS LOCALES',
            'cloud_data': 'DATOS EN LA NUBE',
            'wallet_entries': 'Entradas de cartera',
            'group_expenses': 'Gastos de grupo',
            'groups': 'Grupos',
            'ai_chat_sessions': 'Sesiones de chat IA',
            'wallet_synced': 'Entradas de cartera (sincronizadas)',
            'group_expenses_synced': 'Gastos de grupo (sincronizados)',
            'groups_created': 'Grupos creados',
            'download_report': 'Descargar informe',
            'wallet_report': 'Informe de cartera',
            'wallet_report_sub': 'Tus entradas de cartera personales en PDF',
            'groups_report': 'Informe de grupos',
            'groups_report_sub': 'Todos tus gastos de grupo en PDF',
            'export_data': 'Exportar mis datos',
            'privacy_policy': 'Política de privacidad',
            'export_failed': 'Error al exportar: {error}',
            'json_export': 'JSON \u2014 exportación completa',
            'csv_export': 'CSV \u2014 hoja de cálculo',
            'pdf_report': 'Informe PDF',
        },
        'fr': {
            'title': 'Données et confidentialité',
            'local_data': 'DONNÉES LOCALES',
            'cloud_data': 'DONNÉES CLOUD',
            'wallet_entries': 'Entrées du portefeuille',
            'group_expenses': 'Dépenses de groupe',
            'groups': 'Groupes',
            'ai_chat_sessions': 'Sessions de chat IA',
            'wallet_synced': 'Entrées du portefeuille (synchronisées)',
            'group_expenses_synced': 'Dépenses de groupe (synchronisées)',
            'groups_created': 'Groupes créés',
            'download_report': 'Télécharger le rapport',
            'wallet_report': 'Rapport portefeuille',
            'wallet_report_sub': 'Vos entrées de portefeuille personnelles en PDF',
            'groups_report': 'Rapport des groupes',
            'groups_report_sub': 'Toutes vos dépenses de groupe en PDF',
            'export_data': 'Exporter mes données',
            'privacy_policy': 'Politique de confidentialité',
            'export_failed': 'Échec de l\'export : {error}',
            'json_export': 'JSON \u2014 export complet',
            'csv_export': 'CSV \u2014 tableur',
            'pdf_report': 'Rapport PDF',
        },
        'ka': {
            'title': 'მონაცემები და კონფიდენციალურობა',
            'local_data': 'ლოკალური მონაცემები',
            'cloud_data': 'CLOUD მონაცემები',
            'wallet_entries': 'საფულის ჩანაწერები',
            'group_expenses': 'ჯგუფის ხარჯები',
            'groups': 'ჯგუფები',
            'ai_chat_sessions': 'AI ჩატის სესიები',
            'wallet_synced': 'საფულის ჩანაწერები (სინქრონიზებული)',
            'group_expenses_synced': 'ჯგუფის ხარჯები (სინქრონიზებული)',
            'groups_created': 'შექმნილი ჯგუფები',
            'download_report': 'ანგარიშის გადმოწერა',
            'wallet_report': 'საფულის ანგარიში',
            'wallet_report_sub': 'თქვენი პირადი საფულის ჩანაწერები PDF ფორმატში',
            'groups_report': 'ჯგუფების ანგარიში',
            'groups_report_sub': 'თქვენი ყველა ჯგუფის ხარჯი PDF ფორმატში',
            'export_data': 'მონაცემების ექსპორტი',
            'privacy_policy': 'კონფიდენციალურობის პოლიტიკა',
            'export_failed': 'ექსპორტი ვერ მოხდა: {error}',
            'json_export': 'JSON \u2014 სრული ექსპორტი',
            'csv_export': 'CSV \u2014 ცხრილი',
            'pdf_report': 'PDF ანგარიში',
        },
        'ru': {
            'title': 'Данные и конфиденциальность',
            'local_data': 'ЛОКАЛЬНЫЕ ДАННЫЕ',
            'cloud_data': 'ОБЛАЧНЫЕ ДАННЫЕ',
            'wallet_entries': 'Записи кошелька',
            'group_expenses': 'Расходы группы',
            'groups': 'Группы',
            'ai_chat_sessions': 'Сессии AI-чата',
            'wallet_synced': 'Записи кошелька (синхронизированы)',
            'group_expenses_synced': 'Расходы группы (синхронизированы)',
            'groups_created': 'Созданные группы',
            'download_report': 'Скачать отчёт',
            'wallet_report': 'Отчёт кошелька',
            'wallet_report_sub': 'Личные записи кошелька в формате PDF',
            'groups_report': 'Отчёт по группам',
            'groups_report_sub': 'Все расходы группы в формате PDF',
            'export_data': 'Экспортировать данные',
            'privacy_policy': 'Политика конфиденциальности',
            'export_failed': 'Ошибка экспорта: {error}',
            'json_export': 'JSON \u2014 полный экспорт',
            'csv_export': 'CSV \u2014 таблица',
            'pdf_report': 'PDF-отчёт',
        },
    },
    'security_screen': {
        'en': {
            'title': 'Security',
            'biometrics': 'Biometrics',
            'biometrics_unavailable': 'Biometrics not available on this device.',
            'face_id': 'Face ID / Fingerprint',
            'require_on_open': 'Require on app open',
            'grace_period': 'Grace period',
            'pin_section': 'PIN',
            'set_pin': 'Set PIN',
            'change_pin': 'Change PIN',
            'pin_active': 'PIN is active',
            'no_pin': 'No PIN set',
            'remove_pin': 'Remove PIN',
            'account_password': 'Account Password',
            'change_password': 'Change Password',
            'change_password_sub': 'Update your account login password',
            'dialog_set_pin_title': 'Set PIN',
            'dialog_change_pin_title': 'Change PIN',
            'dialog_pin_fallback': 'Used as fallback when biometrics fail.',
            'dialog_pin_label': 'PIN (4\u20138 digits)',
            'dialog_confirm_pin': 'Confirm PIN',
            'dialog_pin_min': 'PIN must be at least 4 digits',
            'dialog_pin_mismatch': 'PINs do not match',
            'dialog_cancel': 'Cancel',
            'dialog_save_pin': 'Save PIN',
            'pin_saved': 'PIN saved',
            'dialog_remove_pin_title': 'Remove PIN',
            'dialog_remove_pin_body': 'Enter your current PIN to confirm removal.',
            'dialog_current_pin': 'Current PIN',
            'dialog_incorrect_pin': 'Incorrect PIN',
            'dialog_remove': 'Remove',
        },
        'de': {
            'title': 'Sicherheit',
            'biometrics': 'Biometrie',
            'biometrics_unavailable': 'Biometrie ist auf diesem Gerät nicht verfügbar.',
            'face_id': 'Face ID / Fingerabdruck',
            'require_on_open': 'Beim App-Start erforderlich',
            'grace_period': 'Toleranzzeit',
            'pin_section': 'PIN',
            'set_pin': 'PIN festlegen',
            'change_pin': 'PIN ändern',
            'pin_active': 'PIN ist aktiv',
            'no_pin': 'Kein PIN gesetzt',
            'remove_pin': 'PIN entfernen',
            'account_password': 'Konto-Passwort',
            'change_password': 'Passwort ändern',
            'change_password_sub': 'Aktualisiere dein Konto-Anmeldepasswort',
            'dialog_set_pin_title': 'PIN festlegen',
            'dialog_change_pin_title': 'PIN ändern',
            'dialog_pin_fallback': 'Als Fallback verwendet, wenn Biometrie fehlschlägt.',
            'dialog_pin_label': 'PIN (4\u20138 Ziffern)',
            'dialog_confirm_pin': 'PIN bestätigen',
            'dialog_pin_min': 'PIN muss mindestens 4 Ziffern haben',
            'dialog_pin_mismatch': 'PINs stimmen nicht überein',
            'dialog_cancel': 'Abbrechen',
            'dialog_save_pin': 'PIN speichern',
            'pin_saved': 'PIN gespeichert',
            'dialog_remove_pin_title': 'PIN entfernen',
            'dialog_remove_pin_body': 'Gib deinen aktuellen PIN zur Bestätigung ein.',
            'dialog_current_pin': 'Aktueller PIN',
            'dialog_incorrect_pin': 'Falscher PIN',
            'dialog_remove': 'Entfernen',
        },
        'es': {
            'title': 'Seguridad',
            'biometrics': 'Biometría',
            'biometrics_unavailable': 'La biometría no está disponible en este dispositivo.',
            'face_id': 'Face ID / Huella dactilar',
            'require_on_open': 'Requerir al abrir la app',
            'grace_period': 'Período de gracia',
            'pin_section': 'PIN',
            'set_pin': 'Establecer PIN',
            'change_pin': 'Cambiar PIN',
            'pin_active': 'PIN activo',
            'no_pin': 'Sin PIN',
            'remove_pin': 'Eliminar PIN',
            'account_password': 'Contraseña de cuenta',
            'change_password': 'Cambiar contraseña',
            'change_password_sub': 'Actualiza tu contraseña de inicio de sesión',
            'dialog_set_pin_title': 'Establecer PIN',
            'dialog_change_pin_title': 'Cambiar PIN',
            'dialog_pin_fallback': 'Usado como respaldo cuando falla la biometría.',
            'dialog_pin_label': 'PIN (4\u20138 dígitos)',
            'dialog_confirm_pin': 'Confirmar PIN',
            'dialog_pin_min': 'El PIN debe tener al menos 4 dígitos',
            'dialog_pin_mismatch': 'Los PINs no coinciden',
            'dialog_cancel': 'Cancelar',
            'dialog_save_pin': 'Guardar PIN',
            'pin_saved': 'PIN guardado',
            'dialog_remove_pin_title': 'Eliminar PIN',
            'dialog_remove_pin_body': 'Ingresa tu PIN actual para confirmar la eliminación.',
            'dialog_current_pin': 'PIN actual',
            'dialog_incorrect_pin': 'PIN incorrecto',
            'dialog_remove': 'Eliminar',
        },
        'fr': {
            'title': 'Sécurité',
            'biometrics': 'Biométrie',
            'biometrics_unavailable': 'La biométrie n\'est pas disponible sur cet appareil.',
            'face_id': 'Face ID / Empreinte digitale',
            'require_on_open': 'Requis à l\'ouverture de l\'app',
            'grace_period': 'Délai de grâce',
            'pin_section': 'PIN',
            'set_pin': 'Définir un PIN',
            'change_pin': 'Changer le PIN',
            'pin_active': 'PIN actif',
            'no_pin': 'Aucun PIN défini',
            'remove_pin': 'Supprimer le PIN',
            'account_password': 'Mot de passe du compte',
            'change_password': 'Changer le mot de passe',
            'change_password_sub': 'Mettez à jour votre mot de passe de connexion',
            'dialog_set_pin_title': 'Définir un PIN',
            'dialog_change_pin_title': 'Changer le PIN',
            'dialog_pin_fallback': 'Utilisé comme solution de secours si la biométrie échoue.',
            'dialog_pin_label': 'PIN (4\u20138 chiffres)',
            'dialog_confirm_pin': 'Confirmer le PIN',
            'dialog_pin_min': 'Le PIN doit contenir au moins 4 chiffres',
            'dialog_pin_mismatch': 'Les PIN ne correspondent pas',
            'dialog_cancel': 'Annuler',
            'dialog_save_pin': 'Enregistrer le PIN',
            'pin_saved': 'PIN enregistré',
            'dialog_remove_pin_title': 'Supprimer le PIN',
            'dialog_remove_pin_body': 'Entrez votre PIN actuel pour confirmer la suppression.',
            'dialog_current_pin': 'PIN actuel',
            'dialog_incorrect_pin': 'PIN incorrect',
            'dialog_remove': 'Supprimer',
        },
        'ka': {
            'title': 'უსაფრთხოება',
            'biometrics': 'ბიომეტრია',
            'biometrics_unavailable': 'ბიომეტრია მიუწვდომელია ამ მოწყობილობაზე.',
            'face_id': 'Face ID / თითის ანაბეჭდი',
            'require_on_open': 'საჭიროა აპის გახსნისას',
            'grace_period': 'შეღავათის პერიოდი',
            'pin_section': 'PIN',
            'set_pin': 'PIN-ის დაყენება',
            'change_pin': 'PIN-ის შეცვლა',
            'pin_active': 'PIN აქტიურია',
            'no_pin': 'PIN არ არის დაყენებული',
            'remove_pin': 'PIN-ის წაშლა',
            'account_password': 'ანგარიშის პაროლი',
            'change_password': 'პაროლის შეცვლა',
            'change_password_sub': 'განაახლეთ თქვენი ანგარიშის შესვლის პაროლი',
            'dialog_set_pin_title': 'PIN-ის დაყენება',
            'dialog_change_pin_title': 'PIN-ის შეცვლა',
            'dialog_pin_fallback': 'გამოიყენება სარეზერვოდ ბიომეტრიის წარუმატებლობისას.',
            'dialog_pin_label': 'PIN (4\u20138 ციფრი)',
            'dialog_confirm_pin': 'PIN-ის დადასტურება',
            'dialog_pin_min': 'PIN უნდა შეიცავდეს მინიმუმ 4 ციფრს',
            'dialog_pin_mismatch': 'PIN-ები არ ემთხვევა',
            'dialog_cancel': 'გაუქმება',
            'dialog_save_pin': 'PIN-ის შენახვა',
            'pin_saved': 'PIN შენახულია',
            'dialog_remove_pin_title': 'PIN-ის წაშლა',
            'dialog_remove_pin_body': 'შეიყვანეთ მიმდინარე PIN წაშლის დასადასტურებლად.',
            'dialog_current_pin': 'მიმდინარე PIN',
            'dialog_incorrect_pin': 'არასწორი PIN',
            'dialog_remove': 'წაშლა',
        },
        'ru': {
            'title': 'Безопасность',
            'biometrics': 'Биометрия',
            'biometrics_unavailable': 'Биометрия недоступна на этом устройстве.',
            'face_id': 'Face ID / Отпечаток пальца',
            'require_on_open': 'Требовать при открытии приложения',
            'grace_period': 'Льготный период',
            'pin_section': 'PIN',
            'set_pin': 'Установить PIN',
            'change_pin': 'Изменить PIN',
            'pin_active': 'PIN активен',
            'no_pin': 'PIN не установлен',
            'remove_pin': 'Удалить PIN',
            'account_password': 'Пароль учётной записи',
            'change_password': 'Изменить пароль',
            'change_password_sub': 'Обновите пароль входа в учётную запись',
            'dialog_set_pin_title': 'Установить PIN',
            'dialog_change_pin_title': 'Изменить PIN',
            'dialog_pin_fallback': 'Используется как запасной вариант при сбое биометрии.',
            'dialog_pin_label': 'PIN (4\u20138 цифр)',
            'dialog_confirm_pin': 'Подтвердить PIN',
            'dialog_pin_min': 'PIN должен содержать не менее 4 цифр',
            'dialog_pin_mismatch': 'PIN-коды не совпадают',
            'dialog_cancel': 'Отмена',
            'dialog_save_pin': 'Сохранить PIN',
            'pin_saved': 'PIN сохранён',
            'dialog_remove_pin_title': 'Удалить PIN',
            'dialog_remove_pin_body': 'Введите текущий PIN для подтверждения удаления.',
            'dialog_current_pin': 'Текущий PIN',
            'dialog_incorrect_pin': 'Неверный PIN',
            'dialog_remove': 'Удалить',
        },
    },
}

locales = ['en', 'de', 'es', 'fr', 'ka', 'ru']

for section, lang_data in new_keys.items():
    for lang in locales:
        path = f'assets/translations/{lang}.json'
        with open(path, encoding='utf-8') as f:
            d = json.load(f)
        keys = lang_data.get(lang, lang_data.get('en', {}))
        d.setdefault(section, {}).update(keys)
        with open(path, 'w', encoding='utf-8') as f:
            json.dump(d, f, ensure_ascii=False, indent=2)
    print(f'Added {section} to all locales')

print('Done.')
